use_frameworks!


source 'https://github.com/iOSModularization/AHFMSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'AHFMNetworking_Example' do
  pod 'AHFMNetworking', :path => '../'

  target 'AHFMNetworking_Tests' do
    inherit! :search_paths

    
  end
end
